#!/usr/bin/env php
<?php

class PathResolver
{
	public static function path_to_folder()
	{
		$folders = func_get_args();

		return self::get_absolute_path(implode('/', $folders));
	}

	public static function get_absolute_path($path)
	{
		$path = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $path);
		$parts = array_filter(explode(DIRECTORY_SEPARATOR, $path), 'strlen');
		$absolutes = array();

		foreach ($parts as $part) {
			if ('.' == $part) continue;
			
			if ('..' == $part) {
				array_pop($absolutes);
			} else {
				$absolutes[] = $part;
			}
		}

		return implode(DIRECTORY_SEPARATOR, $absolutes);
	}
}

class DirectoryScanner extends PathResolver
{
	private $exclude_folders = array('.', '..');
	private $exclude_extensions = array();

	public function __construct($options = array())
	{
		$this->exclude_folders = isset($options['exclude_folders']) ? $options['exclude_folders'] : $this->exclude_folders;
		$this->exclude_extensions = isset($options['exclude_extensions']) ? $options['exclude_extensions'] : $this->exclude_extensions;
	}

	public function scan($root_folder, $callback) {
		$root_folder = self::path_to_folder($root_folder);

		$folders = scandir($root_folder);

		foreach($folders as $folder) {
			$current_path = self::path_to_folder($root_folder, $folder);

			if(is_dir($current_path)) {
				if(in_array($folder, $this->exclude_folders)) {
					continue;
				}

				$callback($folder, $current_path, true);
			} elseif(is_file($current_path)) {
				if(in_array(pathinfo($current_path, PATHINFO_EXTENSION), $this->exclude_extensions)) {
					continue;
				}

				$callback($folder, $current_path, false);
			}
		}
	}

	public function clean($dir, $remove_root = false)
	{
		$this->scan($dir, function ($filename, $path, $is_dir) {
			if($is_dir) {
				$this->clean($path);

				rmdir($path);
			} else {
				unlink($path);
			}
		});

		if($remove_root) {
			rmdir($dir);
		}
	}
}

class Post
{
	private $filename;
	private $file;
	private $parsed_filename = array();

	private $meta;
	private $content;

	private $post_name_pattern = "/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})-(?P<name>[a-zA-Z_-]+)\.(?P<ext>\w+)/";
	private $post_folder_format = "%year/%month/%day";
	private $post_filename_format = "%name.html";

	private $file_meta_start = "```json\r\n";
	private $file_meta_end = "```\r\n";

	private $allowed_post_filename_options = array(
		'year',
		'month',
		'day',
		'name',
		'ext'
	); 

	public function __construct($options)
	{
		$this->filename = $options['filename'];
		$this->file = file($options['path']);

		$this->parseFilename();
	}

	private function parseFilename()
	{
		preg_match($this->post_name_pattern, $this->filename, $matches);

		foreach($matches as $key => $value) {
			if(in_array($key, $this->allowed_post_filename_options)) {
				$this->parsed_filename[$key] = $value;
			}
		}
	}

	public function getFolder()
	{
		$folder = $this->post_folder_format;

		foreach($this->parsed_filename as $key => $value) {
			$folder = str_replace("%$key", $value, $folder);
		}

		return $folder;
	}

	public function getFilename()
	{
		$folder = $this->post_filename_format;

		foreach($this->parsed_filename as $key => $value) {
			$folder = str_replace("%$key", $value, $folder);
		}

		return $folder;
	}

	public function handle()
	{
		$this->parseFile();

		var_dump($this->getMeta());
	}

	private function parseFile()
	{
		$meta = array();
		$content = array();

		$meta_flag = false;

		foreach($this->file as $line) {
			if($line === $this->file_meta_start) {
				$meta_flag = true;
				
				continue;
			}
			
			if($line === $this->file_meta_end) {
				$meta_flag = false;
				
				continue;
			}

			if($meta_flag) {
				$meta[] = $line;
			} else {
				$content[] = $line;
			}
		}

		$this->setMeta(implode("\r\n", $meta));
		$this->setContent(implode("\r\n", $content));
	}

	private function setMeta($meta)
	{
		$this->meta = json_decode($meta, true);
	}

	private function setContent($content)
	{
		$this->content = $content;
	}

	public function getContent()
	{
		return $this->content;
	}

	public function getMeta()
	{
		return $this->meta;
	}
}

class Blog
{
	private $scanner;
	private $dir_posts;
	private $dir_dist;

	private $post_folder_permissions = 0744;

	public function __construct($options)
	{
		$this->dir_posts = $options['dir_posts'];
		$this->dir_dist = $options['dir_dist'];
		$this->scanner = $options['scanner'];

		$this->path_resolver = new PathResolver();
	}

	public function build()
	{
		$this->scanner->clean($this->dir_dist, false);

		$this->scanLocales($this->dir_posts);
	}

	private function scanLocales($dir)
	{
		$this->scanner->scan($dir, function ($filename, $path, $is_dir) {
			if($is_dir) {
				$this->createLocale($filename);
			
				$this->scanPosts($path, $filename);
			}
		});
	}

	private function createLocale($locale)
	{
		mkdir($this->path_resolver->path_to_folder($this->dir_dist, $locale));
	}

	private function scanPosts($dir, $locale)
	{
		$this->scanner->scan($dir, function ($filename, $path, $is_dir) use($locale) {
			if(!$is_dir) {
				$this->createPost($locale, $filename, $path);
			}
		});
	}

	private function createPost($locale, $filename, $path)
	{
		$post = new Post(array(
			'filename' => $filename,
			'path' => $path,
		));

		$post_folder = $this->path_resolver->path_to_folder(
			$this->dir_dist,
			$locale,
			$post->getFolder()
		);

		if(!file_exists($post_folder)) {
			mkdir($post_folder, $this->post_folder_permissions, true);
		}

		$post->handle();

		file_put_contents($this->path_resolver->path_to_folder($post_folder, $post->getFilename()), $post->getContent());
	}
}

$blog = new Blog(array(
	'dir_posts' => __DIR__ . "/_posts",
	'dir_dist' => __DIR__ . "/www",

	'scanner' => new DirectoryScanner(),
));

$blog->build();

